.main-stand: &main-stand
  tags:
    - walnut
    - build-stand
  only: 
    - dev
    - master

.package-builder: &package-builder
  tags:
    - ssh-docker
    - walnut


stages:
  - ci-debug
  - build
#   - test
  - deploy
  - healthcheck

build-deb-package:
  <<: *package-builder
  stage: ci-debug
  script:
    - ls -la

# build-deb-package:
#   <<: *main-stand
#   stage: build
#   script:
#         - dpkg-buildpackage -us -uc -b
#         - mv ../*.deb ./
#   artifacts:
#     paths:
#         - ./*.deb

pre-deploy:
  <<: *main-stand
  stage: deploy
  script:
    - redis-cli FLUSHALL || true
    - sudo apt purge walnut -y || true
  when: manual

deploy:
  <<: *main-stand
  stage: deploy
  environment: 
    name: build-stand
    url: https://$CI_ENVIRONMENT_SLUG.ratsky.local
  dependencies: 
    - build-deb-package
  script:
    - sudo apt install ./walnut*.deb -y
  needs:
    - pre-deploy
    - build-deb-package
  when: on_success 
  
  

deploy-status:
  <<: *main-stand
  stage: healthcheck
  script:
    - sleep 5
    - sudo systemctl status walnut.target || true
    - sudo systemctl status walnut-observer.service || journalctl -u walnut-observer.service
    - sudo systemctl status walnut-master.service || journalctl -u walnut-master.service
    - sudo systemctl status walnut-django.service || journalctl -u walnut-django.service
  needs:
    - deploy
  when: on_success 
